[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_sanaol = "DuR2A1djtv4vvRgGC9uqntpFo1LQEEUduayDQjXM7qqY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/denrei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
