[toolchain]

[features]
seeds = false

[programs.localnet]
solana_sanaol = "DuR2A1djtv4vvRgGC9uqntpFo1LQEEUduayDQjXM7qqY"

[programs.devnet]
solana_sanaol = "DuR2A1djtv4vvRgGC9uqntpFo1LQEEUduayDQjXM7qqY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/denrei/.config/solana/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
